### ISSUE TITLE
problem with taskio

### ISSUE THREAD

**Issue by Chris166** [dropout1337/Discord-Token-Creator#24]
Traceback (most recent call last):
  File "gen.py", line 162, in <module>
    asyncio.get_event_loop().run_until_complete(client.start())
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "gen.py", line 156, in start
    async with taskio.TaskPool(self.tasks) as pool:
AttributeError: module 'taskio' has no attribute 'TaskPool'

**Comment by Wick9999** [comment]
pip install TaskPool ig

**Comment by nimaisox** [comment]
taskio
pip install taskio
enter command cmd

**Comment by lucciouss** [comment]
> 

still gives that error for me, even thought i did "pip install taskio"

**Comment by nimaisox** [comment]
@lucciouss 

Hi
What an error?

**Comment by baderq99** [comment]
try "pip install tasksio" 
I gor same error but with tasksio and 
pip install tasksio has fix that
